### ISSUE TITLE
Replace the retry option with a data only approach

### ISSUE THREAD

**Issue by avillega** [resonatehq/resonate-sdk-ts#121]
## Describe the problem you are facing
The retry option is represented by an IRetry object that encodes the retry policy for a resonate function invocation. This approach makes it hard to serialize the retry option and store it as part of the durable promise.

## Describe the solution you'd like
Make the retry option an union type of the different retry policies supported by Resonate. it could have this form.
```ts
  interface Exponential = {
    kind: "exponential";
    initialDelay: number;
    backoffFactor: number;
    maxAttemps: number;
    ....
  }
  interface Linear = {
    kind: "linear";
    initialDelay: number;
    maxAttempst: number,
    ....
  }
  interface Never = {
    kind: "never";
  }

  type RetryPolicy = Exponential | Linear | Never;
```

Based on this data we can then run the retry function specified by `kind`.
This approach has the benefit to be trivially serializable and can be stored with the DurablePromise, allowing it to be used in the recovery path of the function.

## Additional context
IRetry was a very flexible way to express the Retry behaviour, allowing for users to implement their own retry policy or extend one of the provided without having to modify the sdk code. How ever, it is still possible to implement your own retry policy by extending the RetryPolicy type directly in the sdk.

**Comment by dfarr** [comment]
Nice, I love this!

**Comment by avillega** [comment]
#122 Implements this proposal.
