### ISSUE TITLE
Dsitrubte as ES Modules

### ISSUE THREAD

**Issue by daniel-nagy** [resonatehq/resonate-sdk-ts#49]
I see in your TypeScript configuration you are outputting CommonJS. https://github.com/resonatehq/resonate-sdk-ts/blob/38f2163e97611cd1864fb758947db99753d94114/tsconfig.json#L28

I would advise outputting ES modules instead. I would also recommend using [TypeScript project references](https://www.typescriptlang.org/docs/handbook/project-references.html) for multiple typescript configuration files. That way you can get proper type checking for both your build and your tests.

**Comment by vaibhawvipul** [comment]
This is done. We are now supporting es modules.
