### ISSUE TITLE
npm distribution incident

### ISSUE THREAD

**Issue by vaibhawvipul** [resonatehq/resonate-sdk-ts#87]
## Incident Details:

**Issue:** empty npm registry package.
**Description:** This incident occurred due to issues with npm distribution during a switch from CommonJS to ES Modules. Initially, it was caused by a configuration problem where noEmit was set to false, resulting in the publishing of an empty package to the npm registry. The problem resurfaced during a release workflow where the npm build step was missing.

### First Incident:
**Cause:** **noEmit** set to false, resulting in an empty package being published.
**Resolution:** Configuration issue identified and corrected after review. 
**Action Taken:** Added a verification step in ci/cd which checks if build was successful or not by importing from /dist folder.

### Second Incident:
**Cause:** Missing npm build step in release workflow. Since this is a separate workflow from the ci/cd, the build verification was not present in this workflow.
**Resolution:** Build step added after review.
**Note:** A verification step was already added to verify if the npm publish is successful or not. But this was not able to identify the bug in time. We need to revisit and fix it.

## Observations:

**PR review:** No merge was without a PR review.
**Over-Reliance on Automation:** Both incidents highlight an over-reliance on automation without adequate manual verification.
**Lack of QA:** The absence of a quality assurance process contributed to the oversight of critical steps in the release workflow.

## Action Items: 
- **More details in the PR** - Every PR should have a proof of QA by the author. We can have screenshots for manual verification. Without that PR should not be merged.
- **Implement Manual Verification:** The manual testing should be done in form of a checklist. This checklist is to be created by the author of the PR and also should be added in the PR information.
- **Enhance Automation:** Strengthen quality assurance procedures to prevent similar incidents in the future.
- **QA report in the ticket:**  Once a PR is merged then before closing the ticket we should add manual entry about the QA which was done after merging the PR to main.

**Comment by vaibhawvipul** [comment]
@dtornow @dfarr @guergabo  please review this and please add your inputs. Thank you.

**Comment by dtornow** [comment]
> **Note**: A verification step was already added to verify if the npm publish is successful or not. But this was not able to identify the bug in time. We need to revisit and fix it.

AFAIU the verification step "checks if build was successful or not by importing from /dist folder". Can you detail why this didn't trigger?

**Comment by vaibhawvipul** [comment]
> > **Note**: A verification step was already added to verify if the npm publish is successful or not. But this was not able to identify the bug in time. We need to revisit and fix it.
> 
> AFAIU the verification step "checks if build was successful or not by importing from /dist folder". Can you detail why this didn't trigger?

Added the following information - 
Since this is a separate workflow from the ci/cd, the build verification was not present in this workflow.

**Comment by dfarr** [comment]
The verification step is included in the updated release workflow #88
